/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as CourierIndexRouteImport } from './routes/courier.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopsShopIdRouteImport } from './routes/shops.$shopId'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerPaymentsRouteImport } from './routes/seller.payments'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerBillingRouteImport } from './routes/seller.billing'
import { Route as RiderHistoryRouteImport } from './routes/rider.history'
import { Route as RiderBoardRouteImport } from './routes/rider.board'
import { Route as RiderBillingRouteImport } from './routes/rider.billing'
import { Route as ProductsSearchRouteImport } from './routes/products.search'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CourierOfficesRouteImport } from './routes/courier.offices'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRegionsRouteImport } from './routes/admin.regions'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminCouriersRouteImport } from './routes/admin.couriers'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'

const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const CourierIndexRoute = CourierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => ShopsRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPaymentsRoute = SellerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerBillingRoute = SellerBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SellerRoute,
} as any)
const RiderHistoryRoute = RiderHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RiderRoute,
} as any)
const RiderBoardRoute = RiderBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => RiderRoute,
} as any)
const RiderBillingRoute = RiderBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => RiderRoute,
} as any)
const ProductsSearchRoute = ProductsSearchRouteImport.update({
  id: '/products/search',
  path: '/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const CourierOfficesRoute = CourierOfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => CourierRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouriersRoute = AdminCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AdminRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/referrals': typeof ReferralsRoute
  '/rider': typeof RiderRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/shops': typeof ShopsRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/courier/offices': typeof CourierOfficesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/search': typeof ProductsSearchRoute
  '/rider/billing': typeof RiderBillingRoute
  '/rider/board': typeof RiderBoardRoute
  '/rider/history': typeof RiderHistoryRoute
  '/seller/billing': typeof SellerBillingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payments': typeof SellerPaymentsRoute
  '/seller/products': typeof SellerProductsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courier/': typeof CourierIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/referrals': typeof ReferralsRoute
  '/shops': typeof ShopsRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/courier/offices': typeof CourierOfficesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/search': typeof ProductsSearchRoute
  '/rider/billing': typeof RiderBillingRoute
  '/rider/board': typeof RiderBoardRoute
  '/rider/history': typeof RiderHistoryRoute
  '/seller/billing': typeof SellerBillingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payments': typeof SellerPaymentsRoute
  '/seller/products': typeof SellerProductsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin': typeof AdminIndexRoute
  '/courier': typeof CourierIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/rider': typeof RiderIndexRoute
  '/seller': typeof SellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/courier': typeof CourierRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/referrals': typeof ReferralsRoute
  '/rider': typeof RiderRouteWithChildren
  '/seller': typeof SellerRouteWithChildren
  '/shops': typeof ShopsRouteWithChildren
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/courier/offices': typeof CourierOfficesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/search': typeof ProductsSearchRoute
  '/rider/billing': typeof RiderBillingRoute
  '/rider/board': typeof RiderBoardRoute
  '/rider/history': typeof RiderHistoryRoute
  '/seller/billing': typeof SellerBillingRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payments': typeof SellerPaymentsRoute
  '/seller/products': typeof SellerProductsRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courier/': typeof CourierIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/seller/': typeof SellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/courier'
    | '/orders'
    | '/referrals'
    | '/rider'
    | '/seller'
    | '/shops'
    | '/account/addresses'
    | '/account/profile'
    | '/admin/couriers'
    | '/admin/pricing'
    | '/admin/referrals'
    | '/admin/regions'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/courier/offices'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/search'
    | '/rider/billing'
    | '/rider/board'
    | '/rider/history'
    | '/seller/billing'
    | '/seller/orders'
    | '/seller/payments'
    | '/seller/products'
    | '/shops/$shopId'
    | '/admin/'
    | '/courier/'
    | '/orders/'
    | '/rider/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/referrals'
    | '/shops'
    | '/account/addresses'
    | '/account/profile'
    | '/admin/couriers'
    | '/admin/pricing'
    | '/admin/referrals'
    | '/admin/regions'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/courier/offices'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/search'
    | '/rider/billing'
    | '/rider/board'
    | '/rider/history'
    | '/seller/billing'
    | '/seller/orders'
    | '/seller/payments'
    | '/seller/products'
    | '/shops/$shopId'
    | '/admin'
    | '/courier'
    | '/orders'
    | '/rider'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/courier'
    | '/orders'
    | '/referrals'
    | '/rider'
    | '/seller'
    | '/shops'
    | '/account/addresses'
    | '/account/profile'
    | '/admin/couriers'
    | '/admin/pricing'
    | '/admin/referrals'
    | '/admin/regions'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/courier/offices'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/search'
    | '/rider/billing'
    | '/rider/board'
    | '/rider/history'
    | '/seller/billing'
    | '/seller/orders'
    | '/seller/payments'
    | '/seller/products'
    | '/shops/$shopId'
    | '/admin/'
    | '/courier/'
    | '/orders/'
    | '/rider/'
    | '/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CourierRoute: typeof CourierRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  ReferralsRoute: typeof ReferralsRoute
  RiderRoute: typeof RiderRouteWithChildren
  SellerRoute: typeof SellerRouteWithChildren
  ShopsRoute: typeof ShopsRouteWithChildren
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsSearchRoute: typeof ProductsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/rider/': {
      id: '/rider/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof RiderRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/courier/': {
      id: '/courier/'
      path: '/'
      fullPath: '/courier/'
      preLoaderRoute: typeof CourierIndexRouteImport
      parentRoute: typeof CourierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/payments': {
      id: '/seller/payments'
      path: '/payments'
      fullPath: '/seller/payments'
      preLoaderRoute: typeof SellerPaymentsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/billing': {
      id: '/seller/billing'
      path: '/billing'
      fullPath: '/seller/billing'
      preLoaderRoute: typeof SellerBillingRouteImport
      parentRoute: typeof SellerRoute
    }
    '/rider/history': {
      id: '/rider/history'
      path: '/history'
      fullPath: '/rider/history'
      preLoaderRoute: typeof RiderHistoryRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/board': {
      id: '/rider/board'
      path: '/board'
      fullPath: '/rider/board'
      preLoaderRoute: typeof RiderBoardRouteImport
      parentRoute: typeof RiderRoute
    }
    '/rider/billing': {
      id: '/rider/billing'
      path: '/billing'
      fullPath: '/rider/billing'
      preLoaderRoute: typeof RiderBillingRouteImport
      parentRoute: typeof RiderRoute
    }
    '/products/search': {
      id: '/products/search'
      path: '/products/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/courier/offices': {
      id: '/courier/offices'
      path: '/offices'
      fullPath: '/courier/offices'
      preLoaderRoute: typeof CourierOfficesRouteImport
      parentRoute: typeof CourierRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/couriers': {
      id: '/admin/couriers'
      path: '/couriers'
      fullPath: '/admin/couriers'
      preLoaderRoute: typeof AdminCouriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCouriersRoute: typeof AdminCouriersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminRegionsRoute: typeof AdminRegionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouriersRoute: AdminCouriersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminRegionsRoute: AdminRegionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CourierRouteChildren {
  CourierOfficesRoute: typeof CourierOfficesRoute
  CourierIndexRoute: typeof CourierIndexRoute
}

const CourierRouteChildren: CourierRouteChildren = {
  CourierOfficesRoute: CourierOfficesRoute,
  CourierIndexRoute: CourierIndexRoute,
}

const CourierRouteWithChildren =
  CourierRoute._addFileChildren(CourierRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface RiderRouteChildren {
  RiderBillingRoute: typeof RiderBillingRoute
  RiderBoardRoute: typeof RiderBoardRoute
  RiderHistoryRoute: typeof RiderHistoryRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

const RiderRouteChildren: RiderRouteChildren = {
  RiderBillingRoute: RiderBillingRoute,
  RiderBoardRoute: RiderBoardRoute,
  RiderHistoryRoute: RiderHistoryRoute,
  RiderIndexRoute: RiderIndexRoute,
}

const RiderRouteWithChildren = RiderRoute._addFileChildren(RiderRouteChildren)

interface SellerRouteChildren {
  SellerBillingRoute: typeof SellerBillingRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPaymentsRoute: typeof SellerPaymentsRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerBillingRoute: SellerBillingRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPaymentsRoute: SellerPaymentsRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

interface ShopsRouteChildren {
  ShopsShopIdRoute: typeof ShopsShopIdRoute
}

const ShopsRouteChildren: ShopsRouteChildren = {
  ShopsShopIdRoute: ShopsShopIdRoute,
}

const ShopsRouteWithChildren = ShopsRoute._addFileChildren(ShopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CourierRoute: CourierRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  ReferralsRoute: ReferralsRoute,
  RiderRoute: RiderRouteWithChildren,
  SellerRoute: SellerRouteWithChildren,
  ShopsRoute: ShopsRouteWithChildren,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsSearchRoute: ProductsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
